name = "uwu"

[kernel]
kernel = "arch/x86_64/boot/bzImage"
rev = "dd7af14795682986f6f77705f8c9c8dade7adcf6"
version = "v6.13"

[xfstests]
rev = "v2024.12.01"
args = "-s xfs_4k generic/572"
test_dev = "/dev/vdb"
scratch_dev = "/dev/vdc"
hooks = "/home/aalbersh/Projects/kernel/fsverity/hooks"

[xfsprogs]
rev = "v6.13.0"

[dummy]
script = "./test.sh"
